version: '3.9'


networks:
  postgres-database:
    external: true


services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
    - postgres-database
    environment:
      TZ: 'Europe/Moscow'
      PGTZ: 'Europe/Moscow'
      POSTGRES_PASSWORD: 'efX579io2qDqajZU1'
      POSTGRES_USER: 'mydatabase'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    networks:
    - postgres-database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - 80:80